### ISSUE TITLE
您好，我有几个问题，希望解答。我想问一下我训练的结果是这样子的，这会是哪里出错了呢？

### ISSUE THREAD

**Issue by leidaguo** [DetectionTeamUCAS/FPN_Tensorflow#41]
数据是这样的
![q 5ybyc 40k3u n11y](https://user-images.githubusercontent.com/29405786/51321637-4669bb00-1a9e-11e9-8a23-240a6375c6d1.png)

但训练结果却是这样的，这是为啥？
 
图一，这是结果，我的xml文件画出图没问题。**问题一**：是不是制作tfrecord的时候出错？
![1](https://user-images.githubusercontent.com/29405786/51324733-6b622c00-1aa6-11e9-9e65-fdb52d283e0f.png)
图二
![2](https://user-images.githubusercontent.com/29405786/51324738-71580d00-1aa6-11e9-80a2-471dae420b42.png)
图三，损失图
![3](https://user-images.githubusercontent.com/29405786/51324776-892f9100-1aa6-11e9-8e03-f05b2a67dbf1.png)
图4，
![4](https://user-images.githubusercontent.com/29405786/51324836-a95f5000-1aa6-11e9-90c0-a1fdffbf857b.png)
图5：**问题2**：这个图是什么意思？
![5](https://user-images.githubusercontent.com/29405786/51324948-e1ff2980-1aa6-11e9-8002-70c1bf33219a.png)
图6：
![6](https://user-images.githubusercontent.com/29405786/51325431-da8c5000-1aa7-11e9-966c-2c75c729a0af.png)
图7：
![7](https://user-images.githubusercontent.com/29405786/51325455-e710a880-1aa7-11e9-9873-d84bf467ab6c.png)
**问题3**：针对这种类型的数据，如果要更好的训练，需要将图6那里设置为自己的数据吗？图7的1,和2参数应该如何改？

**问题4**，这个代码我训练起来很慢，大概1000张图，单1080ti，走完150000需要20小时，这正常吗？有什么提速方法吗？

非常希望您能够回答我的问题，非常感谢！

**Comment by shutian1986** [comment]
您好，请问您是用Python哪个版本训练的啊？训练自己数据的存储路径该怎么定义啊？

**Comment by leidaguo** [comment]
@shutian1986  我用的是2.7，存储路径在https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/data/io/convert_data_to_tfrecord.py

**Comment by shutian1986** [comment]
麻烦再问一下是不是先把自己的数据集制作成VOC格式（就是图像和xml文件那种数据集格式）然后再用convert_data_to_tfrecord.py转换成TensorFlow的训练数据格式！您能把训练数据文件夹截个图吗？一直没弄明白该怎么构建自己的数据集！非常感谢！！！

**Comment by leidaguo** [comment]
是的

**Comment by yangxue0827** [comment]
问题一的gt可视化就可以看出你的坐标存反了 @leidaguo @shutian1986

**Comment by leidaguo** [comment]
@yangxue0827 感谢您的回答，那问题2,3,4呢？

**Comment by shutian1986** [comment]
请问训练自己的数据就包括两个类别，airplane和background需要改哪些文件啊？read_tfrecord.py的第76行该怎么改啊？

**Comment by shutian1986** [comment]
麻烦问一下，为什么我运行完convert_data_to_tfrecord以后，在tfrecord文件夹里面生成的pascal_train.tfrecord文件是空的啊？纠结很久了？麻烦帮解答一下

**Comment by shutian1986** [comment]
请问训练自己数据的时候出现了这样的错误？
 tensorflow.python.framework.error_impl.UNknownError:exception.KeyError:2
  [Node: Pyfunc_1 = Pyfunc_1[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT DT_FLOAT] TOUT=[DT_UINT8], token="pyfunc_16", _dev ice="/job:location/replica:0/task:0:cpu:0"](Squeeze_9), StopGradient_1,postprocess_fastrcnn/Gather_6,StopGradient_2]
Caused by op u 'PyFunc_1', defined at
File train.py, line 186 in <model>
train()
File"train.py", line84, in train
scores=final_scores
File="../lib/box_utiles/show_box_in_tensor.py", line 64, in draw_boxes_with_categories_and_scores.......

**Comment by shutian1986** [comment]
请问训练自己数据的时候出现了这样的错误？
tensorflow.python.framework.error_impl.UNknownError:exception.KeyError:2
[Node: Pyfunc_1 = Pyfunc_1Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT DT_FLOAT] TOUT=[DT_UINT8], token="pyfunc_16", _dev ice="/job:location/replica:0/task:0:cpu:0", StopGradient_1,postprocess_fastrcnn/Gather_6,StopGradient_2]
Caused by op u 'PyFunc_1', defined at
File train.py, line 186 in 
train()
File"train.py", line84, in train
scores=final_scores
File="../lib/box_utiles/show_box_in_tensor.py", line 64, in draw_boxes_with_categories_and_scores.......
@yangxue0827 , @leidaguo

**Comment by yangxue0827** [comment]
别用太高版本的tf @shutian1986

**Comment by shutian1986** [comment]
不少意思再问一个问题，程序能训练了，但是为什么GPU不工作啊，是CPU，我的电脑cuda是cuda.8，在config.py里相对应的CUDA改成8了?是系统的原因吗？ @yangxue0827

**Comment by yangxue0827** [comment]
在cfgs里检查一下gpu的id @shutian1986

**Comment by shutian1986** [comment]
您好，cfgs.py里只有一句关于cuda的那个CUDA9=TRUE,能直接改成CUDA8=TRUE，没有关于GPU id的设置啊，麻烦您能再帮看看嘛？非常感谢！！！

**Comment by shutian1986** [comment]
您好，cfgs.py里只有一句关于cuda的那个CUDA9=TRUE,能直接改成CUDA8=TRUE，没有关于GPU id的设置啊，麻烦您能再帮看看嘛？非常感谢！！！ @yangxue0827

**Comment by yangxue0827** [comment]
cuda9=false   gpu group 这个参数 @shutian1986

**Comment by shutian1986** [comment]
您好，现在这个文件里的 gpu group =4 这个参数该如何根据我电脑的配置设置啊？

**Comment by yangxue0827** [comment]
4表示调用你电脑的第五块gpu @shutian1986 所以根据你gpu数量调整，只有一块就改为0
